## general ##
include:
  - project: "infra/gitlab-ci-templates"
    ref: main
    file:
      - "/general/build-image-with-kaniko.yml"
      - "/general/k8s-deploy.yml"
      - "/general/scan-with-sonarqube.yml"
      - "/general/notify.yml"
      # - "/general/dependency-scanning.yml"

stages:
  - test
  - build-image
  - deploy
  - notify

## Global variables ##
variables:
  RUNNER_TAG: &RUNNER_TAG shared-k8s-runner
  IMAGE_TAG_PREFIX: infigate
  SERVICE_NAME: simshop-dtc-frontend
  ALTERNATIVE_IMAGE_TAG: ${CI_COMMIT_TAG}

default:
  tags:
    - *RUNNER_TAG

#
#scan-sonarqube:
#  stage: build-image
#  extends: .sonarqube-scan-template
#  before_script:
#    - mkdir -p target
#  rules:
#    - if: '$CI_COMMIT_TAG =~ /^prod_[0-9]{4}\.[0-9]{2}\.[0-9]{2}_v[0-9]+$/'
#  variables:
#    SONAR_PROJECT_KEY: ${SERVICE_NAME}

build-image:
  stage: build-image
  extends: .build-image-with-kaniko-template
  rules:
    - if: '$CI_COMMIT_TAG =~ /^(dev|prod)_[0-9]{4}\.[0-9]{2}\.[0-9]{2}_v[0-9]+$/'
  variables:
    DOCKERFILE: Dockerfile

notify:telegram:
  stage: notify
  needs: ["build-image"]
  extends: .notify-telegram-template
  rules:
    - if: '$CI_COMMIT_TAG =~ /^prod_[0-9]{4}\.[0-9]{2}\.[0-9]{2}_v[0-9]+$/'

notify:slack:
  stage: notify
  needs: ["build-image"]
  extends: .notify-slack-template
  rules:
    - if: '$CI_COMMIT_TAG =~ /^prod_[0-9]{4}\.[0-9]{2}\.[0-9]{2}_v[0-9]+$/'
  # rules:
  #   - if: '$CI_COMMIT_TAG =~ /^prod_[0-9]{4}\.[0-9]{2}\.[0-9]{2}_v[0-9]+$/'
  #     when: always
  #   - when: never


update-image-tag:dev:
  stage: deploy
  needs: ["build-image"]
  extends: .update-k8s-deployment-image-tag
  variables:
    K8S_CLUSTER_NAME: wi-lv-dev
    K8S_NAMESPACE: simshop-dev
    KUBECONFIG_FILE: /usr/local/k8s/.credentials/${K8S_CLUSTER_NAME}
  rules:
    - if: '$CI_COMMIT_TAG =~ /^dev_[0-9]{4}\.[0-9]{2}\.[0-9]{2}_v[0-9]+$/'


notify:telegram:after-deploy:
  stage: notify
  needs: ["update-image-tag:dev"]
  extends: .notify-telegram-template
  variables:
    NOTIFY_ACTION_MSG: "✅ Image deployed!"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^dev_[0-9]{4}\.[0-9]{2}\.[0-9]{2}_v[0-9]+$/'

notify:slack:after-deploy:
  stage: notify
  needs: ["update-image-tag:dev"]
  extends: .notify-slack-template
  variables:
    NOTIFY_ACTION_MSG: "✅ Image deployed!"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^dev_[0-9]{4}\.[0-9]{2}\.[0-9]{2}_v[0-9]+$/'

